# Generated by Django 5.0 on 2024-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_customerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
